// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA8tl1OZrIzZOJJo1KPhY5CXC1IsxZfAo',
    appId: '1:1088583066892:android:3e425dd8131e493fc1d529',
    messagingSenderId: '1088583066892',
    projectId: 'tubebox-139a9',
    databaseURL: 'https://tubebox-139a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubebox-139a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxU8qhXBIbjiqfSCkvt3hsOPWbZZhnAYY',
    appId: '1:1088583066892:ios:c1cf49700ff47cecc1d529',
    messagingSenderId: '1088583066892',
    projectId: 'tubebox-139a9',
    databaseURL: 'https://tubebox-139a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubebox-139a9.appspot.com',
    iosBundleId: 'com.tube.box.entertainment.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6M8hYDW7YCmgJdNki7bWkLa6hQ3QKCGc',
    appId: '1:1088583066892:web:0f3e3eb90d5bc24cc1d529',
    messagingSenderId: '1088583066892',
    projectId: 'tubebox-139a9',
    authDomain: 'tubebox-139a9.firebaseapp.com',
    databaseURL: 'https://tubebox-139a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubebox-139a9.appspot.com',
    measurementId: 'G-XRMRXP1GY3',
  );

}